name: Release Pull Request

on:
  pull_request:
    types: [closed]
    branches: [develop, main]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        name: Create/Modify Pull Request
        if: github.event.pull_request.merged && !contains(github.event.pull_request.labels.*.name, 'autorelease')
        id: version
        with:
          release-type: simple
          token: ${{ secrets.VERSION_TOKEN }}
          skip-github-release: true
