name: Release Pull Request

on:
  pull_request:
    branches: [develop, main]
    types: [closed]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        name: Create Release
        id: release
        if: ${{ github.event.pull_request.merged }}
        with:
          release-type: simple
          token: ${{ secrets.VERSION_TOKEN }}

      - name: Publish Package
        if: ${{ steps.release.outputs.release_created }}
        run: echo 'Published ${{steps.release.outputs.major}}.${{steps.release.outputs.minor}}.${{steps.release.outputs.patch}} version'
