name: Release Pull Request

on:
  pull_request:
    branches: [develop, main]
    types: [closed]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        name: Create Release
        id: version
        with:
          token: ${{ secrets.VERSION_TOKEN }}
          config-file: ./.github/workflows/release-please-config.json

      - name: Publish Package
        if: steps.version.outputs.release_created
        run: echo 'Published ${{steps.version.outputs.major}}.${{steps.version.outputs.minor}}.${{steps.version.outputs.patch}} version'
