name: Release Pipeline

on: workflow_dispatch

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        name: Calculate Version
        id: version
        with:
          release-type: simple
          token: ${{ secrets.VERSION_TOKEN }}

      - name: Show Generated Release
        run: "echo ${{ steps.version.outputs.release_created  }}"
