name: Release Pull Request

on:
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch: 

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        name: Create Prerelease
        id: release
        with:
          token: ${{ secrets.VERSION_TOKEN }}
          config-file: .github/workflows/release-config.json
          manifest-file: .github/workflows/.release-manifest.json
          target-branch: main
          

      - name: Publish Package
        if: ${{ steps.release.outputs.release_created }}
        run: echo 'Published ${{steps.release.outputs.major}}.${{steps.release.outputs.minor}}.${{steps.release.outputs.patch}} version'
